[tool.poetry]
name = "cloudflare-ddns"
version = "0.1.0"
description = ""
authors = ["Yasuaki Uechi <y@uechi.io>"]

[tool.poetry.dependencies]
# python = "^3.8"
cloudflare = "^2.8.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
